# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cutlist_App(object):
    def setupUi(self, Cutlist_App):
        Cutlist_App.setObjectName("Cutlist_App")
        Cutlist_App.resize(700, 500)
        Cutlist_App.setMinimumSize(QtCore.QSize(700, 500))
        Cutlist_App.setMaximumSize(QtCore.QSize(700, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        Cutlist_App.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/saw-blade.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cutlist_App.setWindowIcon(icon)
        self.background_image = QtWidgets.QLabel(Cutlist_App)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/background-img-small.jpg"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.quantity = QtWidgets.QSpinBox(Cutlist_App)
        self.quantity.setGeometry(QtCore.QRect(181, 289, 42, 22))
        self.quantity.setStyleSheet("border-image: url(:/img/GUI/Icons - Graphics/text-field.png);")
        self.quantity.setMinimum(1)
        self.quantity.setObjectName("quantity")
        self.filename = QtWidgets.QLineEdit(Cutlist_App)
        self.filename.setEnabled(True)
        self.filename.setGeometry(QtCore.QRect(37, 114, 199, 21))
        self.filename.setMouseTracking(True)
        self.filename.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.filename.setAcceptDrops(True)
        self.filename.setStyleSheet("border-image: url(:/img/GUI/Icons - Graphics/text-field.png);")
        self.filename.setInputMask("")
        self.filename.setClearButtonEnabled(False)
        self.filename.setObjectName("filename")
        self.browse_btn = QtWidgets.QPushButton(Cutlist_App)
        self.browse_btn.setGeometry(QtCore.QRect(259, 108, 40, 40))
        self.browse_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,200)\n"
"}")
        self.browse_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_btn.setIcon(icon1)
        self.browse_btn.setIconSize(QtCore.QSize(30, 30))
        self.browse_btn.setShortcut("")
        self.browse_btn.setDefault(False)
        self.browse_btn.setFlat(False)
        self.browse_btn.setObjectName("browse_btn")
        self.load_btn = QtWidgets.QPushButton(Cutlist_App)
        self.load_btn.setGeometry(QtCore.QRect(309, 108, 40, 40))
        self.load_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,200)\n"
"}")
        self.load_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/refresh-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_btn.setIcon(icon2)
        self.load_btn.setIconSize(QtCore.QSize(30, 30))
        self.load_btn.setFlat(False)
        self.load_btn.setObjectName("load_btn")
        self.stock_len = QtWidgets.QLineEdit(Cutlist_App)
        self.stock_len.setGeometry(QtCore.QRect(177, 240, 47, 21))
        self.stock_len.setStyleSheet("border-image: url(:/img/GUI/Icons - Graphics/text-field.png);")
        self.stock_len.setObjectName("stock_len")
        self.calculate_btn = QtWidgets.QPushButton(Cutlist_App)
        self.calculate_btn.setGeometry(QtCore.QRect(275, 242, 60, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        self.calculate_btn.setFont(font)
        self.calculate_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.calculate_btn.setAutoFillBackground(False)
        self.calculate_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,200)\n"
"}")
        self.calculate_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_btn.setIcon(icon3)
        self.calculate_btn.setIconSize(QtCore.QSize(50, 50))
        self.calculate_btn.setFlat(False)
        self.calculate_btn.setObjectName("calculate_btn")
        self.minimize_btn = QtWidgets.QPushButton(Cutlist_App)
        self.minimize_btn.setGeometry(QtCore.QRect(600, 20, 35, 25))
        self.minimize_btn.setAutoFillBackground(False)
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,120)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,255)\n"
"}")
        self.minimize_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/minimize-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon4)
        self.minimize_btn.setIconSize(QtCore.QSize(25, 25))
        self.minimize_btn.setFlat(False)
        self.minimize_btn.setObjectName("minimize_btn")
        self.close_btn = QtWidgets.QPushButton(Cutlist_App)
        self.close_btn.setGeometry(QtCore.QRect(650, 15, 35, 35))
        self.close_btn.setAutoFillBackground(False)
        self.close_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,0,0,120)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,0,0,255)\n"
"}")
        self.close_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/GUI/Icons - Graphics/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon5)
        self.close_btn.setIconSize(QtCore.QSize(25, 25))
        self.close_btn.setFlat(False)
        self.close_btn.setObjectName("close_btn")
        self.treated_stock = QtWidgets.QLabel(Cutlist_App)
        self.treated_stock.setGeometry(QtCore.QRect(450, 175, 212, 52))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.treated_stock.setFont(font)
        self.treated_stock.setStyleSheet("font: 24px \"Impact\";")
        self.treated_stock.setTextFormat(QtCore.Qt.RichText)
        self.treated_stock.setObjectName("treated_stock")
        self.untreated_stock = QtWidgets.QLabel(Cutlist_App)
        self.untreated_stock.setGeometry(QtCore.QRect(426, 250, 236, 52))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.untreated_stock.setFont(font)
        self.untreated_stock.setStyleSheet("font: 24px \"Impact\";")
        self.untreated_stock.setTextFormat(QtCore.Qt.RichText)
        self.untreated_stock.setObjectName("untreated_stock")
        self.title_frame = QtWidgets.QFrame(Cutlist_App)
        self.title_frame.setGeometry(QtCore.QRect(-81, 5, 698, 59))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.errors = QtWidgets.QLabel(Cutlist_App)
        self.errors.setGeometry(QtCore.QRect(30, 359, 637, 98))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.errors.setFont(font)
        self.errors.setStyleSheet("font: 16px \"Impact\";")
        self.errors.setText("")
        self.errors.setTextFormat(QtCore.Qt.RichText)
        self.errors.setAlignment(QtCore.Qt.AlignCenter)
        self.errors.setObjectName("errors")
        self.cutlist_name = QtWidgets.QLabel(Cutlist_App)
        self.cutlist_name.setGeometry(QtCore.QRect(19, 149, 370, 32))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cutlist_name.setFont(font)
        self.cutlist_name.setStyleSheet("font: 20px \"Impact\";")
        self.cutlist_name.setText("")
        self.cutlist_name.setTextFormat(QtCore.Qt.RichText)
        self.cutlist_name.setObjectName("cutlist_name")
        self.material_type = QtWidgets.QComboBox(Cutlist_App)
        self.material_type.setGeometry(QtCore.QRect(173, 187, 55, 26))
        self.material_type.setObjectName("material_type")
        self.material_type.addItem("")
        self.background_image.raise_()
        self.quantity.raise_()
        self.filename.raise_()
        self.browse_btn.raise_()
        self.load_btn.raise_()
        self.stock_len.raise_()
        self.calculate_btn.raise_()
        self.treated_stock.raise_()
        self.untreated_stock.raise_()
        self.title_frame.raise_()
        self.minimize_btn.raise_()
        self.close_btn.raise_()
        self.errors.raise_()
        self.cutlist_name.raise_()
        self.material_type.raise_()

        self.retranslateUi(Cutlist_App)
        self.close_btn.clicked.connect(Cutlist_App.close) # type: ignore
        self.minimize_btn.clicked.connect(Cutlist_App.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Cutlist_App)

    def retranslateUi(self, Cutlist_App):
        _translate = QtCore.QCoreApplication.translate
        Cutlist_App.setWindowTitle(_translate("Cutlist_App", "CSV Cutlist Calculator"))
        self.treated_stock.setText(_translate("Cutlist_App", "Treated Stock:"))
        self.untreated_stock.setText(_translate("Cutlist_App", "UnTreated Stock:"))
        self.material_type.setItemText(0, _translate("Cutlist_App", "TYPE"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cutlist_App = QtWidgets.QDialog()
    ui = Ui_Cutlist_App()
    ui.setupUi(Cutlist_App)
    Cutlist_App.show()
    sys.exit(app.exec_())
